### ISSUE TITLE
Product info 

### ISSUE THREAD

**Issue by eelti** [adempiere/adempiere-aesthetic-frontend#15]
Log with GardenWorld Admin

try go to Product info
![image](https://user-images.githubusercontent.com/25960538/109344831-46bc0f00-783d-11eb-85e3-bf02c4eb9a44.png)

The debuger in firefox
![image](https://user-images.githubusercontent.com/25960538/109374827-2ebcad80-7886-11eb-820a-85a7779fd7e6.png)

The console:
![image](https://user-images.githubusercontent.com/25960538/109374920-c6220080-7886-11eb-866e-397f357d3f6c.png)
![image](https://user-images.githubusercontent.com/25960538/109374924-cde1a500-7886-11eb-8ed2-c2f702e61f14.png)
![image](https://user-images.githubusercontent.com/25960538/109374928-d5a14980-7886-11eb-9861-63b85b60b92d.png)

**Comment by e-Evolution** [comment]
I got other error :

Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/ProductInfo?pos=1000000".
    at createRouterError (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2009:15)
    at createNavigationDuplicatedError (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1979:15)
    at HashHistory.confirmTransition (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2272:18)
    at HashHistory.transitionTo (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2204:8)
    at HashHistory.push (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2648:10)
    at eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2964:22)
    at new Promise (<anonymous>)
    at VueRouter.push (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2963:12)
    at Store.setCurrentPOS (webpack-internal:///./src/ADempiere/modules/pos/store/PointOfSales/actions.ts:80:30)
    at Array.wrappedActionHandler (webpack-internal:///./node_modules/vuex/dist/vuex.esm.js:856:23)


![image](https://user-images.githubusercontent.com/786968/110358210-c302df00-8001-11eb-84d8-d3bca31c360d.png)
